# SPDX-FileCopyrightText: 2025 Milesime <213074881+milesime@users.noreply.github.com>
#
# SPDX-License-Identifier: GPL-2.0-only

name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    name: Quality Assurance

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: REUSE compliance check
        uses: fsfe/reuse-action@v5
